version: '2'
services:
  wso2-serviceprovider:
    build: ./Primary
    ports:
     - "9443:9443"
  wso2-identityprovider:
    build: ./Secondary
    volumes:
      - ${PWD}/Secondary/repository/conf/carbon.xml:/opt/wso2/repository/conf/carbon.xml
      - ${PWD}/Secondary/repository/conf/identity/identity.xml:/opt/wso2/repository/conf/identity/identity.xml
    ports:
     - "9444:9444"